default_platform(:android)

platform :android do
  desc "Build and upload to Google Play internal testing"
  lane :beta do
    Dir.chdir("..") do
      sh("fvm flutter build appbundle --release")
    end

    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  desc "Build and upload to Google Play production"
  lane :release do
    Dir.chdir("..") do
      sh("fvm flutter build appbundle --release")
    end

    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
    )
  end
end
